### ISSUE TITLE
message['otherData'] returns a string, not a dict

### ISSUE THREAD

**Issue by qdonnellan** [SpiderOak/flow-python#31]
I'm expecting message['otherData'] to be a dict, but it actually is a string!

```python
@flow.message
def print_message(_, message):
    print type(message['regularMessages'][0]['otherData'])  # unicode!!!!
```

I think it should be a dict, would allow for things like:

```python
@flow.message
def print_message(_, message):
    print message['regularMessages'][0]['otherData']['highlighted']
```

**Comment by qdonnellan** [comment]
Just making notes here, but we load the request w/ `json.loads` here: https://github.com/SpiderOak/flow-python/blob/master/src/flow.py#L461

The requests library provides a `.json()` method on request objects, which might be a better option, and potentially solves the problem (though I haven't tested).

**Comment by qdonnellan** [comment]
After testing, the `json()` method indeed DOES NOT solve out problem :/

**Comment by bytex64** [comment]
Yep, it's awkward in the UI as well. Basically, `otherData` is just an opaque text field in the database, so any structured data inside is JSON serialized.

**Comment by qdonnellan** [comment]
Since this is ostensibly a problem with `flowapp` itself, and not `flow-python`, I think it's proper to close this issue. I've added work-around to the bot boilerplate here: https://github.com/SpiderOak/flowbot-barebones/blob/master/src/bot.py#L158
