### ISSUE TITLE
FindOrgByHash error

### ISSUE THREAD

**Issue by evz** [SpiderOak/flow-python#65]
Hi there. I'm attempting to build a little webhook bot that posts messages into a channel in our Semaphor org and am running into an error when I run it on a server. Traceback looks like:

```
FlowError: FindOrgByHash(<hash removed just in case>) failed: getFromTable failed: Event not found: org <another hash removed just in case>
  File "flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 33, in reraise
    raise value
  File "flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "semabot-d-T5HLYBGAO/bot.py", line 99, in deployments
    flow.send_message(ORG_ID, CHANNEL_ID, message)
  File "flow/flow.py", line 1317, in send_message
    return self._run(**run_kwargs)
  File "flow/flow.py", line 618, in _run
    raise Flow.FlowError(response_data["error"])
``` 

My code is over at https://github.com/datamade/semabot (the main app is in bot.py). I suspect this has something to do with not properly authorizing the bot user or perhaps the app is just not using that authorization? The main reason why I suspect that is because when I run the app locally, everything is fine and I'm able to post messages into my org. Any help / guidance would be appreciated!

**Comment by lucasmrod** [comment]
Hello @evz!

The reason you may be getting that error is that you need to create a "device" on each machine the bot account runs. 

Take a look at: https://github.com/SpiderOak/flow-python/blob/master/samples/install_bot.py, which shows the actions you would need to perform when starting a bot (try `flow.start_up("botbotbot")` and if it fails, try `flow.create_device("botbotbot", recoveryKey/password)`. The `create_device()` is executed only the first time the bot is run on the machine.

Let me know if that fixes the issue.

**Comment by evz** [comment]
Hey there @lucasmrod. That worked! I was just missing the fact that I needed to add the device to the user that I already authorized and was instead making new users (which is kind of a mess). 

One additional question I have is: Is there any problem with calling the `create_device` method multiple times for the same user on the same device? From the `install_bot.py` script it looks like it should just fail silently. I'm just wondering if there is any problem with putting this into the normal startup routine for my webhook. This is what I've got at the moment: https://github.com/datamade/semabot/blob/master/bot.py#L20

**Comment by lucasmrod** [comment]
`create_device` should not be called multiple times on the same device.

You should follow the steps performed by the `install_bot.py`, that is:
Try `start_up` (which tries to start the given account), if that fails, then that means the account does not have a device on the host, therefore run `create_device` (the `create_device` will be executed only once, as `start_up` will always be successful once the device is created). 

Some sample code:
```python
def start_bot(f, bot_username, bot_password):
  try:
    f.start_up(bot_username)
    return
  except:
    print "Account does not have device"
  try:
    f.create_device(bot_username, bot_password)
  except:
    # ... code same as install_bot.py

f = Flow()
start_bot(f, 'bot_username', bot_password)
# use f
```

Let me know if it makes sense.

**Comment by evz** [comment]
Yeah, that completely makes sense. I've adjusted as needed. Thanks!
